jingleProject/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'jingles#home'

  get 'home' => 'jingles#home'

  get 'about' => 'jingles#about'

  get 'jingles' => 'jingles#jingles'

  get 'contact' => 'jingles#contact'

  get 'showbycategory/:id' => 'jingles#showbycategory', as: 'show_by_genre'

  get 'search_results' => 'jingles#search_results', as: 'search_results'

end

jingleProject/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

jingleProject/app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cart_items
  has_many :jingles, through: :cart_items
  belongs_to :customer
end

jingleProject/app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :jingle
  belongs_to :cart
end

jingleProject/app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :province
  has_many :carts
end

jingleProject/app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :jingles

  validates :name, presence: true
end

jingleProject/app/models/info.rb
class Info < ActiveRecord::Base
   mount_uploader :image, ImageUploader
end

jingleProject/app/models/jingle.rb
class Jingle < ActiveRecord::Base
  belongs_to :genre
  has_many :cart_items
  has_many :carts, through: :cart_items

  validates :name, :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }

  mount_uploader :image, ImageUploader
end

jingleProject/app/models/province.rb
class Province < ActiveRecord::Base
  validates :name, presence: true
  has_many :customers
end

jingleProject/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

jingleProject/app/controllers/genre_controller.rb
class GenreController < ApplicationController
end

jingleProject/app/controllers/jingles_controller.rb
class JinglesController < ApplicationController
before_action :set_all_jingles

  def home
    @jin_all = Jingle.all
  end

  def about
    @about_info = Info.first
  end

  def jingles
    @jingles = Jingle.order("name").page(params[:page]).per(2)
    @newest_jingles = Jingle.limit(3).reverse_order
    @onsale_jingles = Jingle.where('price < 250')
    #@all_jingles    = Jingle.all
    @jin_genre      = Genre.all
  end

  def contact
    @our_info = Info.first
  end

  def showbycategory
    @jiny = Genre.first
    @jin_genre = Genre.find(params[:id])
  end

  def search_results
      results = '%' + params[:keyword] + "%"
      @found_jingle = Jingle.where("name LIKE ? OR description LIKE ?", results, results)
      @found_genre = Genre.where("name LIKE ?", results)
  end

  def set_all_jingles
    @all_jingles = Jingle.all
  end
end

jingleProject/app/helpers/application_helper.rb
module ApplicationHelper
end

jingleProject/app/helpers/genre_helper.rb
module GenreHelper
end

jingleProject/app/helpers/jingles_helper.rb
module JinglesHelper
end

jingleProject/app/views/jingles/_drop.html.erb
<div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
    Genres
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="dLabel">
  	<% @jin_genre.each do |gen| %>
    <li role="presentation"><%=link_to gen.name, show_by_genre_path(gen) %></li>
    <%end%>
  </ul>
</div>

jingleProject/app/views/jingles/_drop.html.slim
.dropdown
  button#dropdownMenu1.btn.btn-default.dropdown-toggle aria-expanded="true" data-toggle="dropdown" type="button" 
    | Genres
    span.caret
  ul.dropdown-menu.dropdown-menu-right aria-labelledby="dLabel" role="menu" 
    - @jin_genre.each do |gen|
      li role="presentation" = link_to gen.name, show_by_genre_path(gen)

jingleProject/app/views/jingles/_jingle.html.erb
<li>					
	<p>
	  <strong>Name:</strong>
	  <%= jingle.name %>
	</p>

	<p>
	  <strong>Genre:</strong>
	  <%= jingle.genre.name %>
	</p>

	<p>
	  <strong>Description:</strong>
	  <%= jingle.description %>
	</p>

	<p>
	  <strong>Price:</strong>
	  <%= number_to_currency jingle.price %>
	</p>

	<p>
	  <strong>Lyrics:</strong>
	  <% if jingle.hasLyrics %>
	  Yes
	  <%else%>
	  no
	  <%end%>
	</p>
	
	<div class="quantityField" id="item1">
		<button type="button" id="addMac">Add</button>
	</div>

	<div class="clear"></div>
</li>

jingleProject/app/views/jingles/about.html.erb
<h1><%= @about_info.title %></h1>

<p><%= @about_info.content %></p>
<br>
<p><%= image_tag @about_info.image, :width => 750, :height => 300, :crop => :fill %></p>

jingleProject/app/views/jingles/about.html.slim
h1= @about_info.title
p= @about_info.content
br/
p= image_tag @about_info.image, :width => 750, :height => 300, :crop => :fill

jingleProject/app/views/jingles/contact.html.erb
<h1>Contact Us</h1>
<p><%= @our_info.telephone %></p>

<p><%= @our_info.email %></p>
<br>
<p><%= image_tag @our_info.image, :width => 750, :height => 300, :crop => :fill %></p>

jingleProject/app/views/jingles/contact.html.slim
h1 Contact Us
p= @our_info.telephone
p= @our_info.email
br/
p= image_tag @our_info.image, :width => 750, :height => 300, :crop => :fill

jingleProject/app/views/jingles/home.html.slim
#content
  #sliderFrame
    #slider
      = image_tag "jingle_home.jpg", :alt => "Jingl e Store"
      = image_tag "add.jpg", :alt => "Advertise"
      = image_tag "on_air.jpg", :alt => "Go On Air"
      = image_tag "sound.jpg", :alt => "We Have the Best Recording Gear"
      = image_tag "banner.jpg", :alt => "Making new Ideas"
  article.description
    p
      | Jingl e Store offers a variety of transmission-ready radio and television jingles for   low reasonable prices
      | The radio jingles and drop-ins can be reproduced in part, individually with your radio Slogan / branded. We also offer weekly radio items and a daily news service in mp3!.
    = link_to "Check out our Jingles", jingles_path, class: "myButton"
    .clear
  section.recording
    = image_tag "marketing.jpg", :alt => ""
    p
      | It is incredibly important to have a professional quality recording of your jingle before you try to shop around. Even if a music supervisor loves your jingle, he would not pick it if it's not recorded in broadcast quality. Here at Jingl e Store we make sure that is taken care of.
  section.mixing
    = image_tag "jin.gif", :alt => ""
    p
      | The combination of our award-winning engineers, Jingl e Store brings acoustics and our unrivalled range of traditional and state-of-the-art equipment ensure that we give you the best quality possible.
  section.master
    = image_tag "Broadcast.jpg", :alt => ""
    p
      | Mastering is the final stage in the production process and ensures that the music fits together seamlessly and that it is presented with the best possible sound. It involves editing and compiling the required mixes and tracks in production order, and then producing the final master.
footer
  p#copyright.center © Jingl e Store 2014

jingleProject/app/views/jingles/jingles.html.erb
		<h1>Our Jingles</h1>
			<fieldset id="orderInfo">
				<div class="left">
					<h3>Purchase Your Jingle</h3>
					<ul id="jingles">
						<%= render @jingles %>
					</ul>
					<nav id="pagi"><%= paginate @jingles %></nav>
				</div>
				<div class="right">
					<h3>Cart</h3>
					<ul id="cart">
						<!--
						<li id="cartItem1">
							<p><img src="images/mac.png" alt="imac" /><span>iMac</span><br />
								Quantity: <span>2</span><br />
								Total: <span>$3799.98</span>						
							</p>
							<button id="removeItem1" type="button">Remove</button>
							<div class="clear"></div>
						</li>
						-->
						<li id="noItems">
							<p class="center noitems">No items in your cart</p>
						</li>
						<li id="total">
							<p>Total Order Amount: 
								<span id="cartTotal">$0.00</span>
							<p>
						</li>
					</ul>
					<p id="gotoShipping"><a href="#shippinginfo">Enter your info and payment information</a></p>
				</div>
				<%= render 'drop' %>

				<%= form_tag(search_results_path, method: 'get') do %>
					<%=label_tag(:keyword, "Search by Jingle" ) %>
					<%=text_field_tag(:keyword)%>
					<%= submit_tag("Search")%>
				<%end%>
			</fieldset>

<fieldset id="orderInfo">
	<div class="left">
		<section class="newjingle">
			<p>Our Newest Jingles : </p>
			<table>
				<th>Name</th>
				<th>Price</th>

				<% @newest_jingles.each do |newest| %>
					<tr>
						<td><%=newest.name%></td>
						<td><%=newest.price%></td>
					</tr>
				<%end%>
			</table>
		</section>	
		<section class="onsale">
			<p>Jingles On Sales :</p>
			<table>
				<th>Name</th>
				<th>Price</th>

				<% @onsale_jingles.each do |sale| %>
					<tr>
						<td><%=sale.name%></td>
						<td><%=sale.price%></td>
					</tr>
				<%end%>
			</table>
		</section>
	</div>
</fieldset>

jingleProject/app/views/jingles/jingles.html.slim
h1 Our Jingles
fieldset#orderInfo
  .left
    h3 Purchase Your Jingle
    ul#jingles= render @jingles
    nav#pagi= paginate @jingles
  .right
    h3 Cart
    ul#cart
      /!
        | <li id="cartItem1"
        | <p><img src="images/mac.png" alt="imac" /><span>iMac</span><br /
        | Quantity: <span>2</span><br /
        | Total: <span>$3799.98</span
        | </p
        | <button id="removeItem1" type="button">Remove</button
        | <div class="clear"></div
        | </li
      li#noItems
        p.center.noitems No items in your cart
      li#total
        p
          | Total Order Amount:
          span#cartTotal $0.00
        p
    p#gotoShipping
      a href="#shippinginfo"  Enter your info and payment information
  = render 'drop'
  = form_tag(search_results_path, method: 'get') do
    = label_tag(:keyword, "Search by Jingle" )
    = text_field_tag(:keyword)
    = submit_tag("Search")
fieldset#orderInfo
  .left
    section.newjingle
      p Our Newest Jingles :
      table
        th Name
        th Price
        - @newest_jingles.each do |newest|
          tr
            td= newest.name
            td= newest.price
    section.onsale
      p Jingles On Sales :
      table
        th Name
        th Price
        - @onsale_jingles.each do |sale|
          tr
            td= sale.name
            td= sale.price

jingleProject/app/views/jingles/search_results.html.erb
<div class="left">
	<h3>Purchase Your Jingle</h3>

	<%if @found_jingle.size.zero? %>
		<p>No Jingle found</p>
	<% else %>
		<ul id="jingles">
			<% @found_jingle.each do |jingle| %>
			<li>					
				<p>
				  <strong>Name:</strong>
				  <%= jingle.name %>
				</p>

				<p>
				  <strong>Genre:</strong>
				  <%= jingle.genre.name %>
				</p>

				<p>
				  <strong>Description:</strong>
				  <%= jingle.description %>
				</p>

				<p>
				  <strong>Price:</strong>
				  <%= number_to_currency jingle.price %>
				</p>

				<p>
				  <strong>Lyrics:</strong>
				  <% if jingle.hasLyrics %>
				  Yes
				  <%else%>
				  no
				  <%end%>
				</p>
				
				<div class="quantityField" id="item1">
					<button type="button" id="addMac">Add</button>
				</div>

				<div class="clear"></div>
			</li>
			<%end%>
		</ul>
	<% end %>	
</div>	

jingleProject/app/views/jingles/search_results.html.slim
.left
  h3 Purchase Your Jingle
  - if @found_jingle.size.zero?
    p No Jingle found
  - else
    ul#jingles
      - @found_jingle.each do |jingle|
        li
          p
            strong Name:
            = jingle.name
          p
            strong Genre:
            = jingle.genre.name
          p
            strong Description:
            = jingle.description
          p
            strong Price:
            = number_to_currency jingle.price
          p
            strong Lyrics:
            - if jingle.hasLyrics
              | Yes
            - else
              | no
          #item1.quantityField
            button#addMac type="button"  Add
          .clear

jingleProject/app/views/jingles/showbycategory.html.erb
.left
  h3 Purchase Your Jingle
  ul#jingles
    - @jin_genre.jingles.each do |jingle|
      li
        p
          strong Name:
          = jingle.name
        p
          strong Genre:
          = jingle.genre.name
        p
          strong Description:
          = jingle.description
        p
          strong Price:
          = number_to_currency jingle.price
        p
          strong Lyrics:
          - if jingle.hasLyrics
            | Yes
          - else
            | no
        #item1.quantityField
          button#addMac type="button"  Add
        .clear

jingleProject/app/views/jingles/showbycategory.html.slim
.left
  h3 Purchase Your Jingle
  ul#jingles
    - @jin_genre.jingles.each do |jingle|
      li
        p
          strong Name:
          = jingle.name
        p
          strong Genre:
          = jingle.genre.name
        p
          strong Description:
          = jingle.description
        p
          strong Price:
          = number_to_currency jingle.price
        p
          strong Lyrics:
          - if jingle.hasLyrics
            | Yes
          - else
            | no
        #item1.quantityField
          button#addMac type="button"  Add
        .clear

jingleProject/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JingleProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-no-turbolink>

<%= render 'shared/nav' %>  

<%= yield %>

</body>
</html>

jingleProject/app/views/shared/_nav.html.erb
<header>
    <h1><%= link_to "Jingl e Store", root_path  %></h1> 
    <nav>
        <ul>
            <li role="presentation" class="active"><%= link_to "Home", root_path  %></li>
            <li role="presentation"><%= link_to "About us", about_path %></li>
            <li role="presentation"><%= link_to "Jingles", jingles_path %></li>
            <li role="presentation"><%= link_to "Contact Us", contact_path %></li>
        </ul>
    </nav>
</header>

jingleProject/app/views/shared/_nav.slim
header
  h1 == link_to "Jingl e Store", home_path  
  nav
    ul
      li == link_to "Home", home_path  
      li == link_to "About us", about_path 
      li == link_to "Jingles", jingles_path 
      li == link_to "Contact Us", contact_path